//
//  DataLoc.h
//  edrs
//
//  Created by bchan on 15/12/28.
//  Copyright © 2015年 julyyu. All rights reserved.
//

#import <Foundation/Foundation.h>
@import CoreLocation;

typedef enum{
    DT_AUTOGENERATED=0,
    DT_MANUALLY_PLACED=1
} DATALOC_TYPE;

@interface DataLoc : NSObject<NSCoding>

@property NSUUID*                       uniqueID;
@property NSString*                     name;
@property double                        longitude;
@property double                        latitude;
@property double                        radius;
@property DATALOC_TYPE                  type;

- (id)initWithDictionary:(NSDictionary*)dict;
- (void)encodeWithCoder:(NSCoder *)aCoder;
- (id)initWithCoder:(NSCoder *)aDecoder;


@end
